name: 'Psalm baseline progress'
description: 'Calculates psalm baseline diff'
branding: 
  icon: file-minus
  color: purple
inputs:
  base_ref:
    description: 'git ref to use for calculating the base_score'
    required: false
    default: '${{ github.event.pull_request.base.sha }}'
  head_ref:
    description: 'git ref to use for calculating the head_score'
    required: false
    default: 'HEAD'
  path_to_baseline:
    description: 'Path to the baseline file'
    required: false
    default: './psalm-baseline.xml'
  template_decreased:
    description: 'Template to use when the baseline has decreased'
    required: false
    default: '🍀 Psalm baseline has decreased : **$BASE_SCORE** → **$HEAD_SCORE** _(**${SCORE_DIFF}**)_'
  template_increased:
    description: 'Template to use when the baseline has grown'
    required: false
    default: '📛 Psalm baseline has increased: **$BASE_SCORE** → **$HEAD_SCORE** _(+**${SCORE_DIFF}**)_'
  template_no_change:
    description: 'Template to use when the baseline score hasn''t changed'
    required: false
    default: 'Psalm baseline score remained the same: **$HEAD_SCORE**'
outputs:
  base_score:
    description: 'Baseline score for the pull request base'
  head_score:
    description: 'Baseline score for the pull request head'
  score_diff:
    description: 'Difference between the two scores (head_score - base_score)'
  score_diff_string:
    description: 'Same as `score_diff`, with a `+` prepended for positive numbers'
  output_message:
    description: 'Parsed output based on the `template_*` inputs'
runs:
  using: 'docker'
  image: 'Dockerfile'
  env:
    BASE_REF: ${{ inputs.base_ref }}
    HEAD_REF: ${{ inputs.head_ref }}
    PATH_TO_BASELINE: ${{ inputs.path_to_baseline }}
    TEMPLATE_DECREASED: ${{ inputs.template_decreased }}
    TEMPLATE_INCREASED: ${{ inputs.template_increased }}
    TEMPLATE_NO_CHANGE: ${{ inputs.template_no_change }}
