on:
  pull_request:
jobs:
  test-action:
    runs-on: namespace-profile-psalm-baseline-progress-action
    permissions:
      pull-requests: write
    steps:
      - uses: actions/checkout@v5

      - name: 'Action with default settings'
        id: psalm-baseline-progress-action
        uses: ./

      - name: 'Action without xpath condition'
        uses: ./
        with:
          file_xpath_condition: ''

      - name: 'Action with custom xpath condition'
        uses: ./
        with:
          file_xpath_condition: 'not(starts-with(@src, "test/") or starts-with(@src, "foo/"))'

      - name: Comment on PR
        uses: thollander/actions-comment-pull-request@v3
        with:
          message: ${{ steps.psalm-baseline-progress-action.outputs.output_message }}
          comment-tag: 'psalm_baseline_score_comment'
          create-if-not-exists: ${{ steps.psalm-baseline-progress-action.outputs.score_diff != 0 }} # Only create comment when baseline score changed, but always update existing comment
